image: debian:bullseye

stages:
  - build_and_publish

build_and_publish:docker_image_dockerhub:
  stage: build_and_publish
  when: manual
  only:
    - tags
  script:
    - apt-get update
    - apt-get --yes install docker.io
    - export REGISTRY="docker.io"
    - export REGISTRY_PATH="/uibmz"
    - export REGISTRY_USERNAME="uibmz"
    - export OPSI_VERSION="4.2"
    - export OPSI_BRANCH="development"
    - ./opsi-server/opsi-server.sh build --no-cache
    - ./opsi-server/opsi-server.sh publish

build_and_publish:docker_image_internal:
  stage: build_and_publish
  #when: manual
  only:
    - tags
  script:
    - apt-get update
    - apt-get --yes install docker.io
    - export REGISTRY="docker.uib.gmbh"
    - export REGISTRY_PATH="/opsi"
    - export OPSI_VERSION="4.2"
    - export OPSI_BRANCH="development"
    - ./opsi-server/opsi-server.sh build --no-cache
    - ./opsi-server/opsi-server.sh publish
