version: '3.4'

volumes:
 home:
    driver: local

networks:
  default:
    external:
      name: opsi-server_default

services:
  opsi-client-debian-xfce:
    #build: .
    image: opsi-client-debian-xfce
    volumes:
      - home:/home
    ports:
      - "2222:22"
      - "3389:3389"
    hostname: opsi-client-debian-xfce
    domainname: domain.tld
    #links:
    #  - "opsi.domain.tld:opsi-server_opsi-server_1"
    # Needed for cifs / webdav mount
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    entrypoint: ["/entrypoint.sh"]
