version: '3.4'

x-restart-policy: &restart-policy
  restart: unless-stopped

x-common-variables: &common-variables
  TZ: Europe/Berlin

x-common-mysql-variables: &common-mysql-variables
  MYSQL_DATABASE: opsi
  MYSQL_USER: opsi
  MYSQL_PASSWORD: eeC9ku3iejeiriSh

x-common-redis-variables: &common-redis-variables
  REDIS_PASSWORD: ideeT2aeliesh4oo

x-common-grafana-variables: &common-grafana-variables
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: shai6eeQuuQuuo0a

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  opsi_data:
    driver: local

services:
  mysql:
    image: mariadb:10.7
    <<: *restart-policy
    command: --max_connections=1000 --max_allowed_packet=256M --sort_buffer_size=4M
    environment:
       <<: [*common-variables, *common-mysql-variables]
       MYSQL_ROOT_PASSWORD: oareaNg6Ooz4teik
       MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redislabs/redistimeseries:latest
    <<: *restart-policy
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD --loadmodule /usr/lib/redis/modules/redistimeseries.so"
    environment:
      <<: [*common-variables, *common-redis-variables]
    volumes:
      - redis_data:/data

  grafana:
    image: grafana/grafana:latest
    <<: *restart-policy
    ports:
      - "3000:3000"
    environment:
      <<: [*common-variables, *common-grafana-variables]
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource

  opsi-server:
    #image: docker.uib.gmbh/opsi/opsi-server:4.2-experimental
    image: opsi-server:4.2-experimental
    #build: .
    <<: *restart-policy
    depends_on:
      - mysql
      - redis
    ports:
      - "4447:4447"
      - "69:69/udp"
    hostname: opsi
    domainname: domain.tld
    environment:
      <<: [*common-variables, *common-mysql-variables, *common-grafana-variables, *common-redis-variables]
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      GRAFANA_HOST: grafana
      OPSI_ADMIN_PASSWORD: adminuser
      OPSI_ROOT_PASSWORD:
      # configserver / depotserver
      OPSI_HOST_ROLE: configserver
      # Run tftp server and opsipxeconfd? ("true"/"false")
      OPSI_TFTPBOOT: "true"
      # OPSI_SERVICE_ADDRESS and OPSI_HOST_KEY is needed for depotserver role only
      OPSI_SERVICE_ADDRESS:
      OPSI_HOST_KEY:
      # opsconfd config
      OPSICONFD_GRAFANA_EXTERNAL_URL: http://opsi.domain.tld:3000
      OPSICONFD_LOG_LEVEL: 5
      OPSICONFD_LOG_LEVEL_FILE: 4
    cap_add:
      - SYS_PTRACE
    volumes:
      - opsi_data:/data
